<a href="https://colab.research.google.com/github/asadullah00alimran/LearnPython/blob/main/Cancer_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dataset = pd.read_csv('cancer.csv')
print(dataset)

     diagnosis(1=m, 0=b)  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0                      1        17.99  ...          0.4601                  0.11890
1                      1        20.57  ...          0.2750                  0.08902
2                      1        19.69  ...          0.3613                  0.08758
3                      1        11.42  ...          0.6638                  0.17300
4                      1        20.29  ...          0.2364                  0.07678
..                   ...          ...  ...             ...                      ...
564                    1        21.56  ...          0.2060                  0.07115
565                    1        20.13  ...          0.2572                  0.06637
566                    1        16.60  ...          0.2218                  0.07820
567                    1        20.60  ...          0.4087                  0.12400
568                    0         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [ ]:
x = dataset.drop(columns=['diagnosis(1=m, 0=b)'])
print(x)

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
y = dataset['diagnosis(1=m, 0=b)']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis(1=m, 0=b), Length: 569, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_tarin, y_test = train_test_split(x,y, test_size=0.2)

In [ ]:
print(x_train)

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
118        15.78         22.91  ...          0.3274                  0.12520
35         16.74         21.59  ...          0.4863                  0.08633
532        13.68         16.33  ...          0.2806                  0.07782
522        11.26         19.83  ...          0.2557                  0.07613
50         11.76         21.60  ...          0.2433                  0.06563
..           ...           ...  ...             ...                      ...
109        11.34         21.26  ...          0.2829                  0.08832
499        20.59         21.24  ...          0.2480                  0.08999
441        17.27         25.42  ...          0.2500                  0.07944
178        13.01         22.22  ...          0.2295                  0.05843
216        11.89         18.35  ...          0.3397                  0.08365

[455 rows x 30 columns]

In [ ]:
x_test

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
230       17.050         19.08  ...          0.3109                  0.09061
189       12.300         15.90  ...          0.2482                  0.06306
544       13.870         20.70  ...          0.2249                  0.08492
170       12.320         12.39  ...          0.2827                  0.06771
203       13.810         23.75  ...          0.4432                  0.10860
..           ...           ...  ...             ...                      ...
279       13.850         15.18  ...          0.2955                  0.06912
474       10.880         15.62  ...          0.2581                  0.10800
476       14.200         20.53  ...          0.2534                  0.07858
97         9.787         19.94  ...          0.1934                  0.08988
429       12.720         17.67  ...          0.2165                  0.06025

[114 rows x 30 columns]

In [ ]:
y_tarin

118    1
35     1
532    0
522    0
50     0
      ..
109    0
499    1
441    1
178    0
216    0
Name: diagnosis(1=m, 0=b), Length: 455, dtype: int64

In [ ]:
y_test

230    1
189    0
544    0
170    0
203    1
      ..
279    0
474    0
476    0
97     0
429    0
Name: diagnosis(1=m, 0=b), Length: 114, dtype: int64

In [ ]:
import tensorflow as tf